# Colab Start Section

Step 1 is to upload a copy of your private key. I am assuming your private key is named id_ed25519. If that isn't the case, you'll have to make manual changes.

In [13]:
# Change these of course to what is your email and your GitHub username
EMAIL = "pauleanderson@gmail.com"
USERNAME = "pauleanderson"

In [2]:
from google.colab import files
uploaded = files.upload()

Saving id_ed25519 to id_ed25519


In [3]:
%%bash -s "$EMAIL" "$USERNAME"

rm -rf /root/.ssh/*
mkdir /root/.ssh

mv id_ed25519 /root/.ssh/

chmod 600 /root/.ssh/id_ed25519

git config --global user.email "$1"
git config --global user.name "$2"

In [4]:
%%bash -s "$USERNAME"

eval "$(ssh-agent -s)"

ssh-add ~/.ssh/id_ed25519

ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

git clone git@github.com:anderson-fall-2024/csc-487-$1.git

Agent pid 1978


Identity added: /root/.ssh/id_ed25519 (pauleanderson@gmail.com)
# github.com:22 SSH-2.0-babeld-3d60e350f
Cloning into 'csc-487-instructor'...


In [3]:
%load_ext autoreload
%autoreload 2


from pathlib import Path
home = str(Path.home()) # all other paths are relative to this path. change to something else if this is not the case on your system

import sys
sys.path.insert(0,f"csc-487-{USERNAME}")
sys.path.insert(0,"..")

import py487

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
# For tips on running notebooks in Google Colab, see
# https://pytorch.org/tutorials/beginner/colab
%matplotlib inline

Exercises
========================

In [4]:
import torch

Get Device for Training
=======================

We want to be able to train our model on a hardware accelerator like the
GPU or MPS, if available. Let\'s check to see if
[torch.cuda](https://pytorch.org/docs/stable/notes/cuda.html) or
[torch.backends.mps](https://pytorch.org/docs/stable/notes/mps.html) are
available, otherwise we use the CPU.


#### Exercise 1: Write a function elementwise_addition that takes two tensors A and B of the same shape and returns a tensor that contains the elementwise sum of A and B.

In [10]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

C = py487.functional.elementwise_addition(A,B)
C

tensor([[ 6,  8],
        [10, 12]])

#### Exercise 2: Write a function concatenate_tensors that takes two tensors A and B and concatenates them along a specified dimension.

In [20]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

C = py487.functional.concatenate_tensors(A,B,0)
C

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

#### Exercise 3: Write a function reshape_tensor that takes a tensor A and a target shape new_shape and returns a reshaped tensor. Ensure that the total number of elements remains the same after reshaping.

In [21]:
A = torch.tensor([1, 2, 3, 4, 5, 6])
new_shape = (2, 3)
C = py487.functional.reshape_tensor(A,new_shape)
C

tensor([[1, 2, 3],
        [4, 5, 6]])

#### Exercise 4: Write a function sum_along_dim that takes a 2D tensor A and a dimension dim, and returns the sum of the elements along that dimension.

In [23]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
dim = 1
C = py487.functional.sum_along_dim(A,dim)
C

tensor([ 6, 15])

#### Exercise 5: Write a function matrix_multiply that takes two 2D tensors A and B and returns the result of matrix multiplication of A and B.

In [ ]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

C = py487.functional.matrix_multiply(A,B)
C

In [ ]:
# Good job!
# Woohoo!

# Test your code

In [26]:
%%bash -s "$USERNAME"

cd csc-487-$1/tests
pytest test_Assignment2.py

======================================= test session starts ========================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.5.0
rootdir: /content/csc-487-instructor/tests
plugins: anyio-3.7.1, typeguard-4.3.0
collected 5 items

test_Assignment2.py .....                                                                    [100%]

======================================== 5 passed in 2.66s =========================================


# Colab End Section - Submit your code

In [ ]:
%%bash -s "$USERNAME"

eval "$(ssh-agent -s)"

ssh-add ~/.ssh/id_ed25519

ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

cd csc-487-$1
./command_line_sync.sh